// DONE: Expand these types as needed for your implementation
// - Add additional properties as required
// - Use utility types where appropriate
// - Consider using discriminated unions for different feedback states

export const FeedbackStatusEnum = {
  All: 'All',
  Open: 'Open',
  InProgress: 'In Progress',
  Closed: 'Closed',
} as const;

export const FeedbackCategoryEnum = {
  Bug: 'Bug',
  Feature: 'Feature',
  Improvement: 'Improvement',
  Documentation: 'Documentation',
  Other: 'Other',
} as const;

export type FeedbackStatus =
  (typeof FeedbackStatusEnum)[keyof typeof FeedbackStatusEnum];
export type FeedbackCategory =
  (typeof FeedbackCategoryEnum)[keyof typeof FeedbackCategoryEnum];

// Auto-generated fields type
export type AutoGeneratedFields = {
  id: string;
  createdAt: string;
  updatedAt: string;
};

export interface Feedback extends AutoGeneratedFields {
  title: string;
  description: string;
  category: FeedbackCategory;
  status: Exclude<FeedbackStatus, 'All'>;
  upvotes: number;
}

// Type for feedback creation - omitting auto-generated fields
export type CreateFeedback = Omit<
  Feedback,
  keyof AutoGeneratedFields | 'upvotes'
>;

// Type for feedback updates - all fields are optional
export type UpdateFeedback = Partial<Omit<Feedback, keyof AutoGeneratedFields>>;
